version: '3.1'

services:
  db:
    image: mysql
    restart: always
    ports:
        - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: silmar
      MYSQL_USER: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080